package co.istad.elearninga01m1.features.course;

import co.istad.elearninga01m1.features.category.Category;
import co.istad.elearninga01m1.features.category.CategoryRepo;
import co.istad.elearninga01m1.features.config.security.AuthUtils;
import co.istad.elearninga01m1.features.course.dto.CourseResponse;
import co.istad.elearninga01m1.features.course.dto.CreateCourseRequest;
import co.istad.elearninga01m1.features.course.mapper.CourseMapper;
import co.istad.elearninga01m1.features.instructor.InstructorProfile;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

@Service
@RequiredArgsConstructor
public class CourseServiceImpl implements CourseService {

    private final CourseRepo courseRepository;
    private final CategoryRepo categoryRepository;
    private final CourseMapper courseMapper;

    @Override
    public CourseResponse createCourse(CreateCourseRequest createCourseRequest) {
        // TODO: write your logic
        // Validate slug
        if (courseRepository.existsBySlug(createCourseRequest.slug())) {
            throw new ResponseStatusException(HttpStatus.CONFLICT,
                    "Slug has already been used");
        }

        // Validate category
        Category category = categoryRepository.findById(createCourseRequest.categoryId())
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                        "Category has not been found"));

        // Transfer data from DTO to Domain Model
        Course course = courseMapper
                .mapCreateCourseRequestToCourse(createCourseRequest);

        // System data (generated by system)
        course.setCategory(category);
        course.setCountRating(0);
        course.setStarRating(0F);
        course.setIsDeleted(false);
        course.setIsPublished(false);
        course.setInstructorProfile(new InstructorProfile(AuthUtils.extractUserId()));
        course = courseRepository.save(course);

        return courseMapper.mapCourseToCourseResponse(course);
    }
}